export const CarsFeaturesList = [
  'GPS Navigation System',
  'Child Safety Seat',
  'Bluetooth Connectivity',
  'Rearview Camera',
  'Parking Sensors',
  'Heated Seats',
  'Leather Seats',
  'Sunroof/Moonroof',
  'Keyless Entry',
  'Lane Departure Warning',
  'Automatic Emergency Braking',
  'Wireless Phone Charging',
  'Premium Sound System',
  'Panoramic Sunroof',
  'Heated Steering Wheel',
  'Ventilated Seats',
  'Third-Row Seating',
  'Fog Lights',
  'Rain-Sensing Wipers',
  'Cargo Net',
  'Roof Rack',
];
